<head>
<title>Research</title>
<meta name="Research projects of Guillaume Coqueret"/>
</head>

---
description: "Research projects of Guillaume Coqueret"
---
<br/>  


### Book
#### **Machine learning for factor investing** (with T. Guida)
CRC / Chapman Hall, expected September 2020   
Preorder on <a href="https://www.routledge.com/Machine-Learning-for-Factor-Investing/Coqueret-Guida/p/book/9780367545864" target="_blank">on the publisher's website</a>, <a href="https://www.amazon.fr/Machine-Learning-Investing-Guillaume-Coqueret/dp/0367545861/" target="_blank">Amazon (France)</a> or <a href="https://www.amazon.co.uk/Machine-Learning-Investing-Financial-Mathematics/dp/0367545861/ref=sr_1_2?dchild=1&keywords=coqueret&qid=1587124521&sr=8-2" target="_blank">Amazon (UK)</a>  
**Website**: http://www.mlfactor.com    
**Material**: https://github.com/shokru/mlfactor.github.io/tree/master/material

_____ 

### Published Academic Articles
#### **FINANCE & ECONOMICS**

* A note on implied correlation for bivariate contracts, <br/> **Economics Bulletin**, Forthcoming (2020) (with B. Tavin)
* Stock-specific sentiment and return predictability, <br/> **Quantitative Finance**, Forthcoming (2020) <a href="https://www.tandfonline.com/doi/full/10.1080/14697688.2020.1736314" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3248925" target="_blank">[Working paper]</a>
* Procedural Rationality, Asset Heterogeneity and Market Selection,  <br/>  **Journal of Mathematical Economics**, Vol. 82 (2019), pp. 125-149 (2019) (with B. Tavin)  <a href="https://www.sciencedirect.com/science/article/abs/pii/S0304406819300205" target="_blank">[Link]</a>   <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2952659" target="_blank">[Working paper]</a>   <br />
* Empirical properties of a heterogeneous agent model in large dimensions, <br/>   **Journal of Economic Dynamics & Control**, Vol. 77 (2017), pp. 180-201 <a href="https://www.sciencedirect.com/science/article/pii/S0165188917300386" target="_blank">[Link]</a>  
* Characteristics-based portfolio choice with leverage constraints, <br/>   **Journal of Banking and Finance**, Vol. 70 (2016), pp. 23-37 (with M. Ammann and J-P. Schade) <a href="https://www.sciencedirect.com/science/article/pii/S0378426616300516" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2736324" target="_blank">[Working paper]</a>  
* An investigation of model risk in a market with jumps and stochastic volatility, <br/>   **European Journal of Operational Research**, Vol. 253 (2016), pp. 648-658 (with B. Tavin) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0377221716301461" target="_blank">[Link]</a>    <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2474223" target="_blank">[Working paper]</a>
* Diversified minimum-variance portfolios, <br/>   **Annals of Finance**, Vol. 11, No. 2 (2015), pp. 221-241 <a href="https://link.springer.com/article/10.1007%2Fs10436-014-0253-x" target="_blank">[Link]</a>    
* Lookback option prices under a spectrally negative tempered-stable model, <br/>   **International Journal of Theoretical and Applied Finance**, Vol. 16, No. 3 (2013)  <a href="https://www.worldscientific.com/doi/abs/10.1142/S021902491350012X" target="_blank">[Link]</a>    

#### **DATA SCIENCE, PROBABILITY & STATISTICS**

* Training trees on tails with applications to portfolio choice, <br/>   **Annals of Operations Research**, Vol. 288 (2020), pp. 181-221 (with T. Guida) <a href="https://link.springer.com/article/10.1007/s10479-020-03539-2" target="_blank">[Link]</a>   <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3403009" target="_blank">[Working paper]</a> 
<a href="http://www.gcoqueret.com/tot.html" target="_blank">[Material]</a>
* Approximate NORTA simulations for virtual sample generation, <br/>   **Expert Systems With Applications**, Vol. 73 (2017), pp. 69-81 <a href="https://www.sciencedirect.com/science/article/pii/S0957417416307096" target="_blank">[Link]</a>    
* On the distribution of the supremum of the spectrally negative stable process with drift, <br/>   **Statistics & Probability Letters**, Vol. 107 (2015), pp. 333-340 <a href="https://www.sciencedirect.com/science/article/pii/S0167715215003314" target="_blank">[Link]</a>     
* Second order risk aggregation with the Bernstein copula, <br/>   **Insurance: Mathematics and Economics**, Vol. 58 (2014), pp. 150-158 <a href="https://www.sciencedirect.com/science/article/pii/S0167668714000882" target="_blank">[Link]</a>    
* Meromorphic Levy-Khintchine exponents with poles of order two, <br/>   **Communications on Stochastic Analysis**, Vol. 7, No. 2 (2013), pp. 179-198  <a href="https://digitalcommons.lsu.edu/cosa/vol7/iss2/1/" target="_blank">[Link]</a>  
* Approximation of probabilistic Laplace transforms and their inverses, <br/>   **Communications in Applied Mathematics and Computational Science**, Vol. 7, No. 2 (2012), pp. 231-246  <a href="https://msp.org/camcos/2012/7-2/p03.xhtml" target="_blank">[Link]</a>    

#### **WINE BUSINESS**

* Herding behavior among wine investors, **Economic Modelling**, Vol. 68 (2018), pp. 318-328 (with B. Aytac and C. Mandou) <a href="https://www.sciencedirect.com/science/article/pii/S0264999317301001" target="_blank">[Link]</a>    
* Optimal wine pricing for restaurants, **Journal of Wine Economics**, Vol. 10, No. 2 (2015), pp. 204-224 <a href="https://www.cambridge.org/core/journals/journal-of-wine-economics/article/optimal-wine-pricing-for-restaurants/A3A972D73E0785CE8E6A606470FC0A0E" target="_blank">[Link]</a>      



_____ 

### In the Practitioner Press

* Machine learning in systematic equity allocation: a model comparison, <br/> **Wilmott Magazine**, Vol. 2018, Issue 98 (2018), pp. 24-33 <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/wilm.10719" target="_blank">[Link]</a>      
* Equity portfolios with improved liability-hedging benefits, <br/>   **Journal of Portfolio Management**, Vol. 43, No. 2 (Winter 2017), pp. 37-49 (with L. Martellini and V. Milhau) <a href="https://jpm.iijournals.com/content/43/2/37" target="_blank">[Link]</a>    

_____ 


### Book Chapter
Ensemble learning applied to quant equity: gradient boosting in a multifactor framework, In **Big Data and Machine Learning in Quantitative Investment**, 2018 (with T. Guida)  

 

_____ 

### Ongoing research
<a href="http://www.gcoqueret.com/horizons.html" target="_blank">Persistence in factor-based supervised learning models</a>

_____ 


### Permanent Working Papers
* Stock returns and the cross-section of characteristics: a tree-based approach (with T. Guida)  <a href="files/TAPA.pdf" target="_blank">[PDF]</a>    
* Estimation of covariance matrices for portfolio optimization (with V. Milhau) - Scientific Beta Research Paper <a href="files/Estim_cov.pdf" target="_blank">[PDF]</a>    
* Equity portfolios with improved liability-hedging benefits - Long Version  (with R. Deguest, L. Martellini and V. Milhau)  <a href="files/OTPP.pdf" target="_blank">[PDF]</a>    
* Risk aggregation with the generalized logistic distribution <a href="files/Logistic.pdf" target="_blank">[PDF]</a>  
* Pricing exotic options in the Finite Moment Log-Stable model <a href="files/FMLS.pdf" target="_blank">[PDF]</a>  

_____ 


### My academic profiles
<a href="http://orcid.org/0000-0002-1596-4086" target="_blank">ORCID</a> &emsp;  <a href="https://www.researchgate.net/profile/Guillaume_Coqueret" target="_blank">Researchgate</a> &emsp;  <a href="https://publons.com/researcher/1352687/guillaume-coqueret" target="_blank">Publons</a>    
  
